logging:
  pattern:
    console: "%d{ISO8601} [%thread] [%-5level] [%logger{0}.%M:%line] - %msg%n%rEx"
  level:
    root: debug
    sun.rmi: INFO
    org.mongodb.driver: INFO
    org.springframework.amqp.rabbit.listener.BlockingQueueConsumer: INFO

spring:
  datasource:
    url: jdbc:mariadb://192.168.35.149:3306/JAKDUK_BATCH_DEV
    username: root
    password: jakduk584
  batch:
    initialize-schema: never
  data:
    mongodb:
      uri: mongodb://192.168.35.138/jakduk_test
    elasticsearch:
      cluster-name: jakduk-elasticsearch
      cluster-nodes: 192.168.35.151:9300,192.168.35.18:9300
      repositories:
        enabled: false
  rabbitmq:
    addresses: 192.168.35.74
    username: admin
    password: wkrenakstp@
    listener:
      simple:
        auto-startup: false

jakduk:
  elasticsearch:
    index-board: jakduk_dev_board
    index-gallery: jakduk_dev_gallery
    index-search-word: jakduk_dev_search_word
    bulk-actions: 10000
    bulk-concurrent-requests: 2
    bulk-flush-interval-seconds: 10
    bulk-size-mb: 50

  storage:
    image-path: /Users/pyohwanjang/storage/image/
    thumbnail-path: /Users/pyohwanjang/storage/thumbnail/
    user-picture-large-path: /Users/pyohwanjang/storage/user/picture/large/
    user-picture-small-path: /Users/pyohwanjang/storage/user/picture/small/

  rabbitmq:
    exchange-name: jakduk-dev
    queues:
      email:
        binding-queue-name: dev.email
        binding-routing-key: dev.email.*
        enabled: false
    routing-keys:
      email-bulk: dev.email.bulk